
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '1D9469F106F6F520D35C9E5A150CEAD2'
    
_lr_action_items = {'IMAGE':([0,],[1,]),'LPAREN':([1,2,4,8,9,10,],[6,7,11,14,15,16,]),'TRIANGLE':([3,],[9,]),'ANIMATE':([0,],[2,]),'COM':([12,13,17,20,21,22,24,25,32,33,34,37,44,45,51,55,],[18,19,23,26,27,28,30,31,38,39,40,42,48,49,53,56,]),'CIRCLE':([3,],[8,]),'ID':([0,6,],[3,12,]),'NUMBER':([7,11,14,15,16,18,19,23,26,27,28,30,31,38,39,40,42,48,49,53,56,],[13,17,20,21,22,24,25,29,32,33,34,36,37,43,44,45,46,51,52,55,57,]),'$end':([5,35,41,47,50,54,58,],[0,-1,-5,-4,-6,-2,-3,]),'CREATEFRAME':([0,],[4,]),'RPAREN':([29,36,43,46,52,57,],[35,41,47,50,54,58,]),'RECTANGLE':([3,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[5,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> CREATEFRAME LPAREN NUMBER COM NUMBER RPAREN','expression',6,'p_init_frame','Animate_Parser.py',12),
  ('expression -> ID RECTANGLE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',11,'p_create_rectangle','Animate_Parser.py',19),
  ('expression -> ID TRIANGLE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',15,'p_create_triangle','Animate_Parser.py',28),
  ('expression -> ID CIRCLE LPAREN NUMBER COM NUMBER COM NUMBER RPAREN','expression',9,'p_create_circle','Animate_Parser.py',38),
  ('expression -> IMAGE LPAREN ID COM NUMBER COM NUMBER RPAREN','expression',8,'p_image','Animate_Parser.py',47),
  ('expression -> ANIMATE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',10,'p_animate','Animate_Parser.py',52),
]
