
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '53CE46370693BFF81DC0B40820498350'
    
_lr_action_items = {'COM':([12,13,17,20,21,22,24,29,32,33,34,40,42,43,51,55,],[18,19,23,26,27,28,30,35,37,38,39,45,46,47,54,56,]),'TRIANGLE':([4,],[9,]),'IMAGE':([0,],[2,]),'$end':([1,31,41,48,52,53,58,],[0,-1,-5,-4,-6,-2,-3,]),'RECTANGLE':([4,],[8,]),'CREATEFRAME':([0,],[3,]),'LPAREN':([2,3,5,8,9,10,],[6,7,11,14,15,16,]),'ID':([0,6,],[4,12,]),'ANIMATE':([0,],[5,]),'RPAREN':([25,36,44,49,50,57,],[31,41,48,52,53,58,]),'NUMBER':([7,11,14,15,16,18,19,23,26,27,28,30,35,37,38,39,45,46,47,54,56,],[13,17,20,21,22,24,25,29,32,33,34,36,40,42,43,44,49,50,51,55,57,]),'CIRCLE':([4,],[10,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> CREATEFRAME LPAREN NUMBER COM NUMBER RPAREN','expression',6,'p_init_frame','Animate_Parser.py',12),
  ('expression -> ID RECTANGLE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',11,'p_create_rectangle','Animate_Parser.py',19),
  ('expression -> ID TRIANGLE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',15,'p_create_triangle','Animate_Parser.py',28),
  ('expression -> ID CIRCLE LPAREN NUMBER COM NUMBER COM NUMBER RPAREN','expression',9,'p_create_circle','Animate_Parser.py',38),
  ('expression -> IMAGE LPAREN ID COM NUMBER COM NUMBER RPAREN','expression',8,'p_image','Animate_Parser.py',47),
  ('expression -> ANIMATE LPAREN NUMBER COM NUMBER COM NUMBER COM NUMBER RPAREN','expression',10,'p_animate','Animate_Parser.py',52),
]
